rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainerTest.java
Fixed #10 
This pr is migrated from here https://github.com/apache/rocketmq-externals/pull/174
Enhance consumer classes so that consumer classes can be inherited
Look for the RocketMQListener interface from the current class, if not found then look up from the parent class until it is found
=> Enhance consumer classes so that consumer classes can be inherited

.travis.yml, pom.xml, rocketmq-spring-boot-parent/pom.xml, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ListenerContainerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
=> [ISSUE-43] Make the README Travis CI works

README.md, README_zh_CN.md, rocketmq-spring-boot-samples/pom.xml, rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/consumer/StringConsumerNewNS.java, rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/resources/application.properties, rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/java/org/apache/rocketmq/samples/springboot/ExtRocketMQTemplate.java, rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/java/org/apache/rocketmq/samples/springboot/ProducerApplication.java, rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/resources/application.properties, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/ExtRocketMQTemplateConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtProducerResetConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ListenerContainerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/config/RocketMQConfigUtils.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfigurationTest.java
1. Add an extra optional property 'nameServer' for @RocketMQMessageListener, to define a different nameserver for Consumer
2. Support to define and use extra RocketMQTemplate, which can have different nameServer or other properties 
For details, please see the README.md and new code in samples.
=> [ISSUE-46] Support mutliple RocketMQTemplate & name-server overrided Consumer Listener

rocketmq-spring-boot-parent/pom.xml, rocketmq-spring-boot/pom.xml
Generate spring-configuration-metadata.json for easy configuration tips.
Generate spring-configuration-metadata.json for easy configuration tips.
maven package Generated spring-configuration-metadata.json
=> Generate spring-configuration-metadata.json for easy configuration tips.

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfiguration.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfigurationTest.java
=> raise a warning log message if no property 'rocketmq.name-server' is defined in application.property

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/RocketMQUtilTest.java
#83 
RocketMQUtil#addUserProperties can override headers from rocketmq(eg topic,tags,queue id...)
Increase the judgment to prohibit the coverage of the rocketmq special attribute.
=> [ISSUE #83]Fixed the issue that addUserProperties will override headers from rocketmq.

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ListenerContainerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQProperties.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfigurationTest.java
control @RocketMQMessageListener service registration when the container boostraped
Add registration configuarion when load ListenerContainerConfiguration
when the service is annotated with `l @RocketMQMessageListener ` and following configuartion is configured, the listener would not be reigsters as a mq consumer.
```
rocketmq.consumer.listeners.<group-name>.<topic-name>.enabled = false
```
By the way, the  `@RocketMQMessageListener `  is registered by default.
=> [ISSUE #86] add feature: consumer listener enabled configuration

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/config/RocketMQTransactionAnnotationProcessor.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfigurationTest.java
[#96](https://github.com/apache/rocketmq-spring/issues/96)  resolve the placeholder for "listener.txProducerGroup()"
resolve the placeholder for "listener.txProducerGroup()" in file RocketMQTransactionAnnotationProcessor.java
when add TransactionListener like this :
```
@RocketMQTransactionListener(txProducerGroup = "${demo.rocketmq.transaction.producer.group}")
class TransactionListenerImpl implements RocketMQLocalTransactionListener {
private static final Logger LOGGER = LoggerFactory.getLogger(TransactionListenerImpl.class);
private AtomicInteger transactionIndex = new AtomicInteger(0);
private ConcurrentHashMap<String, Integer> localTrans = new ConcurrentHashMap<>();
```
the txProducerGroup can be injected from configuation like application.properties file.
=> [ISSUE #96] resolve the placeholder for "listener.txProducerGroup()"

rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/consumer/StringConsumerNewNS.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java
Fix [issue 99](https://github.com/apache/rocketmq-spring/issues/99) and [issue 107](https://github.com/apache/rocketmq-spring/issues/107).
Normally, instanceName is not set and is automatically modified to processId when consumer starts up.
=> [ISSUE 99 & ISSUE 107] Fix the message was consumed twice because of the same instanceName

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ListenerContainerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfigurationTest.java
@RocketMQMessageListener(topic =
"${demo.rocketmq.test.consumer.topic}",selectorExpression="${demo.rocketmq.test.consumer.tags}"
,consumerGroup = "${demo.rocketmq.test.consumer.group}")
purpose to support resolvePlaceholders for selectorExpression
modify ListenerContainerConfiguration.java
modify DefaultRocketMQListenerContainer.java
=> [ISSUE #103]Support resolvePlaceholders for selectorExpression

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java
#163 
Fix transactionProducer has incorrect namespace
Set namespace when createTransactionMQProducer
=> [ISSUE #163] Fix transactionProducer has incorrect namespace

rocketmq-spring-boot-samples/pom.xml, rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/consumer/MessageExtConsumer.java, rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/consumer/User.java, rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/consumer/UserConsumer.java, rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/domain/User.java, rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/resources/application.properties, rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/java/org/apache/rocketmq/samples/springboot/ProducerApplication.java, rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/java/org/apache/rocketmq/samples/springboot/domain/User.java, rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/resources/application.properties, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtProducerResetConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ListenerContainerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/MessageConverterConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/config/TransactionHandlerRegistry.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQMessageConverter.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfigurationTest.java
An enhancement about the convert in RocketMQTemplate
enhancement  #147 
Do not use `ObjectMapper` directly, Instead, the externally built converter is injected into `MessageConverter` in  `RocketMQTemplate`.
a piece of code in `RocketMQMessageConverter` :
```java
public RocketMQMessageConverter() {
List<MessageConverter> messageConverters = new ArrayList<>();
ByteArrayMessageConverter byteArrayMessageConverter = new ByteArrayMessageConverter();
byteArrayMessageConverter.setContentTypeResolver(null);
messageConverters.add(byteArrayMessageConverter);
messageConverters.add(new StringMessageConverter());
if (JACKSON_PRESENT) {
messageConverters.add(new MappingJackson2MessageConverter());
}
if (FASTJSON_PRESENT) {
try {
messageConverters.add(
(MessageConverter)ClassUtils.forName( …
```
=> [ISSUE #147]An enhancement about the convert in RocketMQTemplate

rocketmq-spring-boot-samples/pom.xml, rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/consumer/StringConsumer.java, rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/resources/application.properties, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ListenerContainerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
ref #186 
Fix selectorExpression cannot autoconfigure from configure file
Delete `container.setRocketMQMessageListener(annotation)` in createRocketMQListenerContainer method
XXXX
=> [ISSUE #186]Fix selectorExpression cannot autoconfigure from configure file

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainerTest.java
**Problems:**
When definition the listener like this. the starter cannot settup
`public class Listener1 implements RocketMQListener<MsgDto<String>>`
Recently, I tryied solve this problem,only modify the DefaultRocketMQListenerContainer class.  **Wish to improve the starter in next release.**
1. My Main idea is use org.springframework.messaging.converter.SmartMessageConverter#fromMessage .This interface define a third parameter called "Object conversionHint".
2. I switch the Definition of DefaultRocketMQListenerContainer#messageType to Type insteadof Class
3. add a "private  MethodParameter onMessageParameter" member  to DefaultRocketMQListenerContainer and init it to indicate the onMessage parameter when afterPropertiesSet() 
4. when doCovertMessage. if the messageType instanceof …
=> [ISSUE #197] Solve the problem that RocketMQListener can not deserialize generic onMessage method parameter

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
Fix the Infinite loop in DefaultRocketMQListenerContainer
Adjust the getMessageType method
XXXX
=> [ISSUE #151] Fix the Infinite loop in DefaultRocketMQListenerContainer

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/ExtRocketMQTemplateConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtProducerResetConfiguration.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfigurationTest.java
fix #211 
Remove the limitation that ExtRocketMQTemplate can not keep the same nameserver as RocketMQTemplate
=> [ISSUE #211] Remove the limitation that ExtRocketMQTemplate can not keep the same nameserver as RocketMQTemplate

pom.xml, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java
Fix the bug of BatchMessage syncSend without timeout
https://github.com/apache/rocketmq-spring/issues/242
Add a Method :syncSend(String destination, Collection<T> messages)  will fix the bug. The consumer can lot consume messages .
=> [issue #242]Fix Bug Of BatchMessage SyncSend without timeout param

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java
Fix #241 
Make the unit of consumeTimeout in rocketmq-spring consistent with rocketmq client
XXXX
=> [ISSUE #241] Make the unit of consumeTimeout in rocketmq-spring consistent with rocketmq client

rocketmq-spring-boot-parent/pom.xml
1. To eliminate the vulnerability of the serialization components. [ISSUE #285  ]
1. Upgrade jackson version from 2.9.7 to 2.11.1
2. Upgrade fastjson version from 1.2.69 to 1.2.72
1. Jackson: https://help.aliyun.com/noticelist/articleid/1060035134.html
2. Fastjson: https://help.aliyun.com/noticelist/articleid/1060343604.html
=> [ISSUE #285] Upgrade jackson/fastjson version

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java
XXXXX
从header中获取KEYS参数为空时，尝试添加前缀再次获取。
XXXX
=> [ISSUE #294] GetAndWrapmessage method in rocketmqUtil is missing prefix when getting keys

rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ConsumerACLApplication.java, rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/resources/application.properties, rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/ConsumerApplication.java, rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/ExtRocketMQTemplate.java, rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/resources/application.properties, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/ExtRocketMQConsumerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtConsumerResetConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQProperties.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfigurationTest.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/core/ExtRocketMQTemplateTest.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/core/RocketMQTemplateTest.java
Support LitePullMessage in RocketMQ-Spring. 
Although I have seen a brother submit a PR for a similar function, I think that is not a real pull consumption model, it is no different from the push consumption model. I just focus on the issue, not the person.
An instance of DefaultLitePullConsumer is added to RocketMQTemplate, and the receive method of RocketMQTemplate can be called to consume messages in a pull mode.
=> [ISSUE #306] Support real LitePullMessage in RocketMQ-Spring

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainerTest.java
1. enhence DefaultRocketMQListenerContainer doConvertMessage: 
- support org.apache.rocketmq.common.message.Message
it's more friendly for users to use @RocketMQMessageListener e.g String MessageExt Message
2. add DefaultRocketMQListenerContainerTest UT
1.  enhence DefaultRocketMQListenerContainer doConvertMessage
=> [ISSUE #346] enhence DefaultRocketMQListenerContainer doConvertMessage

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java
issue #378 
In different consumption modes, the meaning of maxReconsumeTimes being -1 is not the same.
In concurrently mode, -1 means 16. In orderly mode, -1 means Integer.MAX_VALUE.
It can give users or source code readers better guidance.
Improve the comment of maxReconsumeTimes.
- [] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).
=> [ISSUE #378]Improve the comment of maxReconsumeTimes

rocketmq-spring-boot-samples/rocketmq-consume-demo/pom.xml, rocketmq-spring-boot-samples/rocketmq-produce-demo/pom.xml, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/ExtRocketMQConsumerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/ExtRocketMQTemplateConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtConsumerResetConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtProducerResetConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQProperties.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
=> [ISSUE #396]support namespace

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQHeaders.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java
[ ISSUE #411 ]
This change support DELAY and WAIT properties  in RocketMQHeaders.java, which can convert Spring-Message to Rocket-Message conveniently.
Because of losting properties of 'DELAY' and 'WAIT' in RocketMQHeaders.java. Without these properties, we will make mistakes when use RocketMQTemplate to send a DELAY-Message or a WAIT-Message.
Support DELAY and WAIT properties  in RocketMQHeaders.java, which can convert Spring-Message to Rocket-Message conveniently.
=> [ISSUE #411] Support DELAY and WAIT properties  in RocketMQHeaders.java, which can convert Spring-Message to Rocket-Message conveniently

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainerTest.java
Use 'consumeThreadNumber' instead of consumeThreadMax , so that the core thread number and max thread number of the consumer thread pool executor has the same thread number.
use consumeThreadNum to adjust consumeThreadMin and consumeThreadMax  at the same time .
XXXX
- [] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one …
=> [ISSUE #429]The 'consumeThreadMax' in annotation @RocketMQMessageListener is not works well

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
feature:Support Consumer Shutdown "awaitTerminationMillisWhenShutdown"
=> [ISSUE #435] Support Consumer Shutdown "awaitTerminationMillisWhenShutdown"

rocketmq-spring-boot-parent/pom.xml
Security fix
New version of Spring which fixes Spring4shell
=> [ISSUE #443] Update Spring to 5.3.18 to fix CVE cve-2022-22965 aka Spring4shell.

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/RocketMQUtilTest.java
#458 #469 
In broadcast subscription mode, set the instanceName of the consumer to namesrvaddr to prevent the project from being unable to read the local consumption offset data after the project is restarted
XXXX
- [] Format the pull request …
=> [ISSUE #458]Fixed the problem of cannot consume previous messages in broadcast consumption mode

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtConsumerResetConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtProducerResetConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ListenerContainerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java
Add defaultNamespace to both producer and consumer 
prefer to use the namespace specified by annotation, or a defaultNamespace from property file will be used.
=> [ISSUE #481] Add defaultNamespace to both producer and consumer . (#481)

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtConsumerResetConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtProducerResetConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ListenerContainerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java
close #494 
- Replace deprecated StringUtils.isEmpty method with StringUtils.hasLength
XXXX
=> [ISSUE #494]Replace deprecated StringUtils.isEmpty method with StringUtils.hasLength

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java
=> [ISSUE #507]Feat: support send oderly delay message for RocketMQTemplate

rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ACLStringConsumer.java, rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ACLStringTransactionalConsumer.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/ExtRocketMQConsumerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ListenerContainerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQProperties.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfigurationTest.java
=> [ISSUE #512]Go back and keep versions compatible

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DelayMode.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/core/RocketMQTemplateTest.java
support send message with arbitrarily delay time
upgrade rocketmq client version to 5.0.0.
add api in RocketMqTemplate to support send message with arbitrarily delay time
=> [ISSUE #506] support send message with arbitrarily delay time

rocketmq-spring-boot/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Fix: #539 Support SpringBoot 3.x.
Springboot-3.0 has abandoned `spring.factories` automatic assembly, it's replace by `/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`, add this file for compatibility.
[reference](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files)
Support SpringBoot 3.x
=> [ISSUE #539] Feat: support SpringBoot 3.x

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
fix #616 
change handleMessage to public, so user can fetch some header info uniformly
```
@Pointcut("execution(* org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.handleMessage*(..))")
private void listenerConsume() {
}
@Around("listenerConsume()")
public Object aroundListenerConsume(ProceedingJoinPoint pjp) throws Throwable {
//do something     
}
```
=> feat: change handleMessage to public

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ListenerContainerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQMessageListenerContainerRegistrar.java
class ListenerContainerConfiguration should be an automatic assembler. Listener container registration should be delegated to other class like "RocketMQMessageListenerContainerRegistrar".
related to https://github.com/apache/rocketmq-spring/issues/536
=> [ISSUE #536]fix: ListenerContainerConfiguration should be an automatic assembler

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfiguration.java
Solve the problem of sending message errors when producers do not configure namespaces。
In the current situation, when the namespace is not configured, the method of setting the namespace is called when instantiating the bean, causing the producer to initialize the namespace to be empty, but 'ClientConfig # namespaceInitialized' is set to true. This leads to the producer sending an error message: "No route information of this topic: xxx"
When instantiating beans ("defaultMQProducer", "defaultLitePullConsumer"), the set namespace method is called only when the namespace is configured。
Verified！
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before …
=> Fix the issue of sending message "No route information of this topic: xxx" when the producer does not configure the namespace

rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/annotation/ExtConsumerResetConfiguration.java, rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/autoconfigure/RocketMQProperties.java
Set rocketmq-v5-client-spring-boot default awaitDuration to 5
Set rocketmq-v5-client-spring-boot default awaitDuration to 5 from 0
=> [ISSUE #656] Set rocketmq-v5-client-spring-boot default awaitDuration to 5

rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/annotation/RocketMQMessageListener.java
The TOPIC_PLACEHOLDER value should be topic rather than endpoints
https://github.com/apache/rocketmq-spring/blob/9f1bc791955f81bb061c301340ae5f79a6fd0a57/rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/annotation/RocketMQMessageListener.java#L33
Set TOPIC_PLACEHOLDER to "${rocketmq.push-consumer.topic:}"
=> Fix RocketMQMessageListener TOPIC_PLACEHOLDER

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/ExtRocketMQConsumerConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/ExtRocketMQTemplateConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtConsumerResetConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtProducerResetConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfiguration.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQProperties.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java, rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQMessageListenerContainerRegistrar.java, rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainerTest.java, rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/annotation/ExtConsumerResetConfiguration.java, rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/annotation/ExtProducerResetConfiguration.java, rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/annotation/RocketMQMessageListener.java, rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/autoconfigure/ExtConsumerResetConfiguration.java, rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/autoconfigure/ExtTemplateResetConfiguration.java, rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/autoconfigure/ListenerContainerConfiguration.java, rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/autoconfigure/RocketMQProperties.java, rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/support/DefaultListenerContainer.java, rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/support/RocketMQUtil.java
close #654
Support namespace for rocketmq-v5-client-spring-boot and rocketmq-spring-boot
Support namespace for rocketmq-v5-client-spring-boot and rocketmq-spring-boot
Add namespace for rocketmq-v5-client-spring-boot and namespaceV2 for rocketmq-spring-boot, it's important to note that in rocketmq-spring-boot, namespaceV2 and namespace cannot be set simultaneously.
=> [ISSUE #654] Support namespace for rocketmq-v5-client-spring-boot and rocketmq-spring-boot

rocketmq-spring-boot-samples/pom.xml, rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/pom.xml, rocketmq-spring-boot-samples/rocketmq-consume-demo/pom.xml, rocketmq-spring-boot-samples/rocketmq-consumer-pull-simple-demo/pom.xml, rocketmq-spring-boot-samples/rocketmq-consumer-push-simple-demo/pom.xml, rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/pom.xml, rocketmq-spring-boot-samples/rocketmq-produce-demo/pom.xml, rocketmq-spring-boot-samples/rocketmq-producer-simple-demo/pom.xml, rocketmq-v5-client-spring-boot-samples/pom.xml, rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-consume-acl-demo/pom.xml, rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-consume-demo/pom.xml, rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-consumer-push-simple-demo/pom.xml, rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-consumer-simple-demo/pom.xml, rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-producer-acl-demo/pom.xml, rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-producer-demo/pom.xml, rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-producer-simple-demo/pom.xml
Updated the RocketMQ version dependencies in the rocketmq-spring-boot-samples and rocketmq-v5-client-spring-boot-samples modules.
- Updated RocketMQ version in rocketmq-spring-boot-samples module
- Updated RocketMQ version in rocketmq-v5-client-spring-boot-samples module
Updated version from 2.3.1-SNAPSHOT to 2.3.2-SNAPSHOT
=> Updated the RocketMQ version dependencies in the rocketmq-spring-boot-samples and rocketmq-v5-client-spring-boot-samples modules.

rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/support/RocketMQHeaders.java, rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/support/RocketMQUtil.java
=> delete sysytem proerty

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
fix #686 
Modify the inner class to call handleMessage as a bean invocation, so that the AOP interception of the handleMessage method can work properly.
```java
@Aspect
@Component
public class RocketMQMessageAspect {
@Pointcut("execution(* org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.handleMessage*(..))")
public void rocketMQConsumerMethod() {}
@Around("rocketMQConsumerMethod()")
public Object logConsumerMethod(ProceedingJoinPoint joinPoint) throws Throwable {
Object[] args = joinPoint.getArgs();
MessageExt messageExt = (MessageExt) args[0];
// do something
return joinPoint.proceed();
}
}
``` 
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is …
=> [ISSUE #686] feat:Modify the inner class call to use the bean instance invocation

rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/core/RocketMQClientTemplate.java
=> [ISSUE #705] Fix future in async send not complete

rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/core/RocketMQClientTemplate.java
Remove unnecessary catch blocks and log statements.
Remove unnecessary catch blocks and log statements.
XXXX
=> Remove unnecessary catch blocks and log statements in syncSendGrpcMessage

rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/autoconfigure/ExtConsumerResetConfiguration.java, rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/autoconfigure/ExtTemplateResetConfiguration.java
Optimize log output
Optimize log output
XXXX
=> Optimize log output
