README.md
README_zh_CN.md
rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/consumer/OrderPaidEventConsumer.java
rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/consumer/StringConsumer.java
rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/consumer/StringTransactionalConsumer.java
rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/resources/application.properties
rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/java/org/apache/rocketmq/samples/springboot/ProducerApplication.java
rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/resources/application.properties
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/config/ListenerContainerConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/config/RocketMQAutoConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/config/RocketMQProperties.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/config/TransactionHandlerRegistry.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/config/RocketMQAutoConfigurationTest.java

1. Fixed for ISSUE #9 : According to spring requirement, third party auto-configurations should not have their configuration keys starting with spring.
Modify configuration properties form spring.rocketmq.XXX to rocketmq.XXX
2. Fixed for ISSUE #7 : remove unnecessary init for ObjectMapper
XXXX

Fixed for [ISSUE-9] & [ISSUE-7]

---

README.md
README_zh_CN.md
rocketmq-spring-boot-samples/README.md
rocketmq-spring-boot-samples/README_zh_CN.md
rocketmq-spring-boot-samples/pom.xml

Use the released depdency version (2.0.1)

[ISSUE-34] Make the sample pom.xml use the released version in mvn repo

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ListenerContainerConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java

[ISSUE #28]enhancement of judgment for consumer target class
replace get target class method AopUtils#getTargetClass with AopProxyUtils#ultimateTargetClass
XXXX

[ISSUE #28]enhancement of judgment for consumer target class

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/RocketMQUtilTest.java

ISSUE #38 
Support payload with byte[] type in message conversion.

[ISSUE #38]support payload with byte[] type in message conversion

---

README.md
README_zh_CN.md
rocketmq-spring-boot-parent/pom.xml
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ACLStringConsumer.java
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ACLStringTransactionalConsumer.java
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ConsumerACLApplication.java
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/resources/application.properties
rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ProducerACLApplication.java
rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/src/main/resources/application.properties
rocketmq-spring-boot/pom.xml
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQTransactionListener.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQProperties.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/config/RocketMQTransactionAnnotationProcessor.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/config/TransactionHandler.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/config/TransactionHandlerRegistry.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java

[ISSUE-47] Support ACL & message trace feature

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQHeaders.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/RocketMQUtilTest.java

As titled.
XX
see RocketMQUtilTest

[ISSUE-41] Optimize header conversion

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java

ISSUE #36 Support delay level configuration in async mode
Add method:
public void asyncSend(String destination, Message<?> message, SendCallback sendCallback, long timeout, int delayLevel)

[ISSUE #36]Support delay level configuration in async mode

---

README.md

#67 
Fix typo in example readme file
Fix typo in example readme file
Fix typo in example readme file

[ISSUE #67]Fix typo in example readme file

---

rocketmq-spring-boot-samples/pom.xml
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ACLStringConsumer.java
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ACLStringTransactionalConsumer.java
rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ProducerACLApplication.java

#74 Add acl examples compile in the project
Add acl examples compile in the project
mvn compile

[ISSUE #74]Add acl examples compile in the project

---

rocketmq-spring-boot-samples/pom.xml

update example version to 2.0.4-snapshot
update example version to 2.0.4-snapshot
check the pom file

Update example version to 2.0.4-snapshot

---

rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ProducerACLApplication.java
rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/java/org/apache/rocketmq/samples/springboot/ProducerApplication.java

Set the correct transaction id identification key for subsequent operations.

Set the correct transaction id identification key for subsequent operations.

---

.travis.yml

Travis moved forward to be not compatible with the old configuration. 
Modify .travis.yml to make travis-ci work.
Add
```
jdk:
- oraclejdk8
```

Modify .travis.yml to make travis-ci work

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java

[ISSUE #117]Fix timeout failed in syncSendOrderly.

---

rocketmq-spring-boot-parent/pom.xml

Upgrade rocketmq dependency to 4.5.2

---

NOTICE
README.md
README_zh_CN.md

fix(doc):update the year in NOTICE and upgrade the version in README
fix(doc):update the year in NOTICE and upgrade the version in README
fix(doc):update the year in NOTICE and upgrade the version in README

fix(doc):update the year in NOTICE and upgrade the version in README

---

pom.xml
rocketmq-spring-boot-parent/pom.xml
rocketmq-spring-boot-samples/pom.xml
rocketmq-spring-boot-starter/pom.xml
rocketmq-spring-boot/pom.xml
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtProducerResetConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQProperties.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java

Polish the code and modify version
link #215 

[ISSUE #215] Polish the code and modify version

---

README.md

add new badge for readme doc
XX
XXXX

Doc(readme):add new badge for readme doc

---

NOTICE

update notice's year to 2020
update notice's year to 2020
XXXX

doc(notice):update notice's year to 2020

---

README.md
rocketmq-spring-boot-samples/pom.xml
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/resources/application.properties
rocketmq-spring-boot-samples/rocketmq-consume-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/resources/application.properties
rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/src/main/resources/application.properties
rocketmq-spring-boot-samples/rocketmq-produce-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/resources/application.properties

Add asf license to properties file and update readme and version of samples
Add asf license to properties file and update readme and version of samples
XXXX

Add asf license to properties file and update readme

---

rocketmq-spring-boot-parent/pom.xml
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java

issue#263
Change the verions of rocketmq's client to 4.7.0
XXXX

[ISSUE #263] Change the verions of rocketmq's client in the pom's file

---

rocketmq-spring-boot-parent/pom.xml
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQProperties.java

Upgrade RocketMQ version to 4.7.1
Upgrade RocketMQ version to 4.7.1
XXXX

[ISSUE #282] Upgrade RocketMQ version to 4.7.1

---

rocketmq-spring-boot-samples/pom.xml
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/RocketMQUtilTest.java

Use the default instance name when using acl
Use the default instance name when using acl
XXXX

[ISSUE# 289] Use the default instance name when using acl

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java

issue#268
Only print the important information of message when consume failed
XXXX

[ISSUE #298] Too many warning info when consuming failed.

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/RocketMQUtilTest.java

issue#268
Set instance name for consumers
XXXX

[ISSUE #268] RocketMQMessageListener nameServer not work

---

rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/java/org/apache/rocketmq/samples/springboot/ProducerApplication.java

Enumeration and number matching errors, and I want to fix it.
Fix the correspondence between enumerations and numbers.

[ISSUE #304]Fix the correspondence between enumerations and numbers.

---

rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ACLStringConsumer.java

A comment error is in ACLStringConsumer class, and I want to fix it.
Fix the comment error in ACLStringConsumer class.

 [ISSUE #308]Fix the comment error in ACLStringConsumer class.

---

rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-consume-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-produce-demo/pom.xml

To compile samples successully
Now ,  project can be  compiled  passed.

[ISSUE #314]  Modify  parent.versions of  modules  in  samples project  from 2.1.1-SNAPSHOT to 2.1.2-SNAPSHOT

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java

To avoid lots of info log. I have described detail in #327 
change log level from info to debug to avoid lots of log

[ISSUE #327] Remove info log in consumeMessage method

---

rocketmq-spring-boot-parent/pom.xml
rocketmq-spring-boot-samples/pom.xml

Upgrade RocketMQ version
Upgrade RocketMQ version
- [] Write …

[ISSUE# 329] Upgrade RocketMQ version

---

NOTICE
README.md

Update notice and  readme document
Update notice and readme document
- [] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line …

[ISSUE #331] Update notice and readme document

---

rocketmq-spring-boot-samples/pom.xml
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-consume-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-produce-demo/pom.xml

Update RocketMQ Spring samples version
Update RocketMQ Spring samples version
- [] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful …

[ISSUE #335] Update rocketmq spring samples version

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/ExtRocketMQTemplateConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQProperties.java

issue #340 
set enableMsgTrace default value to false
XXXX
- [] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. 
- [] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

[ISSUE #340] set enableMsgTrace default value to false

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/RocketMQUtilTest.java

issue #339 
default instance name add @${nanoTime}
XXXX
- [] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

[ISSUE #339] Fix consumer do not consume message with the same instance name

---

rocketmq-spring-boot-samples/pom.xml

[ISSUE #368] Upgrade starter version.

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java

[ISSUE #366] The retry number of failed consumptions can be set.

---

rocketmq-spring-boot-parent/pom.xml

Upgrade rocketmq version to 4.9.1
Upgrade rocketmq version to 4.9.1
XXXX
- [] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject …

[ISSUE #381] Upgrade rocketmq version to 4.9.1

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtConsumerResetConfiguration.java

[ISSUE #376]Fix the selectorExpression not resolve placeholders.

---

rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/consumer/StringConsumerWithReplyString.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainerTest.java

[ISSUE #377]Add the replyTimeout configuration parameter

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java

WAIT_STORE_MSG_OK property parsing error
Fix #365 
XX
XXXX
- …

[ISSUE #365] WAIT_STORE_MSG_OK property parsing error

---

rocketmq-spring-boot-samples/pom.xml

[ISSUE #389] Upgrade rocketmq-samples version to 2.2.2-SNAPSHOT

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java

fix [#402]
supplement rocketmq sync send message failed log out.
Verify

[ISSUE#402] supplement rocketmq sync send message failed log out.

---

rocketmq-spring-boot-parent/pom.xml

[ISSUE #404]Upgrade RocketMQ version to 4.9.2

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/RocketMQUtilTest.java

issue  #417 
Fix the instance name is too long.
Fix the instance name is too long.

[ISSUE #417]Fix the instance name is too long

---

rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/pom.xml

Version synchronization of samples

chore: sample-version-sync

---

rocketmq-spring-boot-parent/pom.xml
rocketmq-spring-boot/pom.xml

https://github.com/apache/rocketmq-spring/issues/427
Avoid CVE in spring-core
pom change
CI build
- [] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

upgrade spring-core and spring-boot due to cve

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainerTest.java

issue #419 
Support consumption retry strategy configuration.
Support consumption retry strategy configuration.

[ISSUE #419]Support consumption retry strategy configuration.

---

rocketmq-spring-boot-parent/pom.xml

[ISSUE #436]Upgrade RocketMQ version to 4.9.3

---

rocketmq-spring-boot-parent/pom.xml
rocketmq-spring-boot/pom.xml
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQMessageConverter.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/RocketMQUtilTest.java

[ISSUE #426]Fix deserialize LocalDateTime failed when using jdk8

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQTransactionListener.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQTransactionConfiguration.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfigurationTest.java

[ISSUE #439] Fix the wrong comment description of the default value in the keepalivetime field of the RocketMQTransactionListener annotation.

---

rocketmq-spring-boot/README.md

For #446 
Correct typos in the document.
XXXX

[ISSUE #446] Correct typos in the document.

---

rocketmq-spring-boot-parent/pom.xml

Upgrade fastjson version to 1.2.83
XX
XXXX
- [] Write a pull …

Upgrade fastjson version to 1.2.83

---

rocketmq-spring-boot-samples/pom.xml
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-consume-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-produce-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/java/org/apache/rocketmq/samples/springboot/ExtRocketMQTemplate.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/ExtRocketMQConsumerConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/ExtRocketMQTemplateConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtConsumerResetConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtProducerResetConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQProperties.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainerTest.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/support/RocketMQUtilTest.java

[ISSUE ##471] Supports instance name config in producer and consumer

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtConsumerResetConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtProducerResetConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ListenerContainerConfiguration.java

It's better to depend on interface than on a concrete class. see issue #477  for detail.
change StandardEnvironment to ConfigurableEnvironment

[ISSUE #477] change StandardEnvironment to ConfigurableEnvironment

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtProducerResetConfiguration.java

[ISSUE #484] Fix testExtRocketMQTemplate

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtConsumerResetConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtProducerResetConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ListenerContainerConfiguration.java

[ISSUE #486]The namespace configuration in the annotation cannot be read

---

.github/PULL_REQUEST_TEMPLATE.md

close #496 
- Fix pull request template format not correct
XXXX
- [] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and …

[ISSUE #496]Fix pull request template format not correct

---

pom.xml

[ISSUE #499] Add apache rat check exclude file

---

rocketmq-spring-boot-parent/pom.xml
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListenerBeanPostProcessorTest.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfigurationTest.java
rocketmq-spring-boot/src/test/java/org/apache/rocketmq/spring/core/RocketMQTemplateTest.java

Support RocketMQ 5.0.0
Support RocketMQ 5.0.0
done
- [] …

[ISSUE #488]Support RocketMQ 5.0.0

---

rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ACLStringConsumer.java
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/java/org/apache/rocketmq/samples/springboot/ACLStringTransactionalConsumer.java
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/src/main/resources/application.properties
rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/resources/application.properties
rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/src/main/resources/application.properties
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/ExtRocketMQConsumerConfiguration.java

Polish the application.properties to solve the misunderstanding between push consumer and pull consumer
Polish the application.properties to solve the misunderstanding between push consumer and pull consumer
XXXX

[ISSUE #511] Polish the application.properties to solve the misunderstanding between push consumer and pull consumer

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java

Close #520 
Add syncSendDeliverTimeMills and syncSendDelayTimeMills API for RocketMQ 5.0 timer message
Add syncSendDeliverTimeMills and syncSendDelayTimeMills API for RocketMQ 5.0 timer message
XXXX

[ISSUE #520] Add syncSendDeliverTimeMills and syncSendDelayTimeMills API for RocketMQ 5.0 timer message

---

rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/java/org/apache/rocketmq/samples/springboot/ProducerApplication.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/ExtConsumerResetConfiguration.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQTransactionConfiguration.java

format code and  optimization description
format code and  optimization description
XXXX

[ISSUE #522] format code and  Optimization description

---

rocketmq-spring-boot-parent/pom.xml
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/RocketMQUtil.java

close #530 
- upgrade rocketmq client version to 5.1.0
XXXX

[ISSUE #530]upgrade rocketmq client version to 5.1.0

---

rocketmq-spring-boot-samples/pom.xml
rocketmq-spring-boot-samples/rocketmq-consume-acl-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-consume-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-produce-acl-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-produce-demo/pom.xml
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java

[maven-release-plugin] prepare for next development iteration.
In addition, fix some syntax errors

[maven-release-plugin] prepare for next development iteration. In addition, fix some syntax errors

---

rocketmq-spring-boot-parent/pom.xml

Upgrade rocketmq SDK version to 5.1.3
Upgrade rocketmq SDK version to 5.1.3
XXXX

[ISSUE #572] Upgrade rocketmq SDK version to 5.1.3

---

rocketmq-v5-client-spring-boot-parent/pom.xml

Bump jackson to 2.16.1
Bump jackson to 2.16.1
XXXX

[ISSUE #607] Bump jackson to 2.16.1

---

rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/autoconfigure/RocketMQAutoConfiguration.java
rocketmq-v5-client-spring-boot/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

Fix: [#612](https://github.com/apache/rocketmq-spring/issues/612) Springboot 3.X
1. Replace `@PostConstruct` with constructor
2. log format style
3. Springboot 3.x autoconfigure
XXXX

[ISSUE #612] Support Springboot 3.X

---

rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/core/RocketMQClientTemplate.java

fix bug when create  rocket mq  producer 
fix bug when create  rocket mq  producer 
fix bug when create  rocket mq  producer 

fix bug when create rocketmq producer

---

rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/autoconfigure/ExtConsumerResetConfiguration.java
rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/autoconfigure/ExtTemplateResetConfiguration.java
rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/autoconfigure/RocketMQAutoConfiguration.java
rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/support/DefaultListenerContainer.java
rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/support/RocketMQUtil.java

[ISSUE #622] add config enableSsl

---

rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/autoconfigure/ExtConsumerResetConfiguration.java
rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/autoconfigure/ExtTemplateResetConfiguration.java
rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/autoconfigure/ListenerContainerConfiguration.java
rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/support/RocketMQUtil.java

[ISSUE #610] fix setRequestTimeout use Duration.ofDays

---

rocketmq-spring-boot-parent/pom.xml

Bump rocketmq version to 5.2.0
Bump rocketmq version to 5.2.0
XXXX

[ISSUE #631] Bump rocketmq version to 5.2.0

---

rocketmq-v5-client-spring-boot-parent/pom.xml

Bump rocketmq.spring.client.version to 5.0.6
Bump rocketmq.spring.client.version to 5.0.6
XXXX

[ISSUE #645] Bump rocketmq.spring.client.version to 5.0.6

---

rocketmq-spring-boot-parent/pom.xml

Exclude rocketmq-rocksdb due to the large size of this package
Exclude rocketmq-rocksdb due to the large size of this package
XXXX

Exclude rocketmq-rocksdb due to the large size of this package

---

NOTICE

update year to 2024 in NOTICE

---

rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/java/org/apache/rocketmq/samples/springboot/ProducerApplication.java
rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/annotation/RocketMQMessageListener.java

Close [https://github.com/apache/rocketmq-spring/issues/650](https://github.com/apache/rocketmq-spring/issues/650)
Fix url 404 and typo
xxxx

[ISSUE #650] Fix url and typo

---

rocketmq-spring-boot-samples/pom.xml
rocketmq-spring-boot-samples/rocketmq-consumer-pull-simple-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-consumer-pull-simple-demo/src/main/java/org/apache/rocketmq/samples/springboot/PullConsumerApplication.java
rocketmq-spring-boot-samples/rocketmq-consumer-pull-simple-demo/src/main/resources/application.properties
rocketmq-spring-boot-samples/rocketmq-consumer-push-simple-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-consumer-push-simple-demo/src/main/java/org/apache/rocketmq/samples/springboot/PushConsumerApplication.java
rocketmq-spring-boot-samples/rocketmq-consumer-push-simple-demo/src/main/resources/application.properties
rocketmq-spring-boot-samples/rocketmq-producer-simple-demo/pom.xml
rocketmq-spring-boot-samples/rocketmq-producer-simple-demo/src/main/java/org/apache/rocketmq/samples/springboot/ProducerApplication.java
rocketmq-spring-boot-samples/rocketmq-producer-simple-demo/src/main/resources/application.properties
rocketmq-v5-client-spring-boot-samples/pom.xml
rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-consumer-push-simple-demo/pom.xml
rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-consumer-push-simple-demo/src/main/java/org/apache/rocketmq/samples/springboot/V5PushConsumerConsumerApplication.java
rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-consumer-push-simple-demo/src/main/resources/application.properties
rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-consumer-simple-demo/pom.xml
rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-consumer-simple-demo/src/main/java/org/apache/rocketmq/samples/springboot/V5SimpleConsumerConsumerApplication.java
rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-consumer-simple-demo/src/main/resources/application.properties
rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-producer-simple-demo/pom.xml
rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-producer-simple-demo/src/main/java/org/apache/rocketmq/samples/springboot/V5ProducerApplication.java
rocketmq-v5-client-spring-boot-samples/rocketmq-v5-client-producer-simple-demo/src/main/resources/application.properties

close #660
Add simple sample demo

[ISSUE #660] Add simple sample demo

---

rocketmq-v5-client-spring-boot-parent/pom.xml

Update rocketmq client version to 5.0.7 in for rocketmq-v5-client
Update rocketmq client version to 5.0.7 in for rocketmq-v5-client

[ISSUE #663] Update rocketmq client version to 5.0.7 in for rocketmq-v5-client

---

rocketmq-v5-client-spring-boot/src/main/java/org/apache/rocketmq/client/support/RocketMQUtil.java

[ISSUE #733] Fix the issue that ClientServiceProvider is initialized every time a message is sent
